start_date: "2025-01-01"    # must be in ISO format YYYY-MM-DD, inclusive
end_date: "2025-12-01"      # must be in ISO format YYYY-MM-DD, exclusive
Granularity: "MONTHLY"
Filter:
    Dimensions:
        Key: "SERVICE"
        Values:
          - "Amazon SageMaker"
        MatchOptions:
          - "EQUALS"
#
#        LinkedAccount:
#            - "123456789012"   # Example Account ID 1
#            - "210987654321"   # Example Account ID 2
#        Service:
#            - "AmazonEC2"
#            - "AmazonS3"
metrics:
    - "BlendedCost"
    - "UnblendedCost"
    - "UsageQuantity"
GroupBy:
    - Type: "DIMENSION"
      Key: "USAGE_TYPE"
    # if group and breakdown by tag
#    - Type: "TAG"
#      Key: "Name"